image: Ubuntu2004

environment:
  DOCKERHUB_PASS:
    secure: o71pevAd3AAskRz34CZIak0HRHKebCm8MM1mE7g9w3dWajlADYoFLR++PXpt5G1MK6fYPQGrjZEqDV6jpN5uPg==
  SSH_ENC_PW:
    secure: dsfg/madWjGDwzbs9mqzVBzsm9yTPuAXDn8p06X5x19HE55oB2/DwLyt2rBdOEhc
  SSH_ENC_SALT:
    secure: SfpYN5CE94KMJwIe+tznDBzhMfMqwdgQxb0uxVS9yVUuzgV5ko6mVx26Er6QRovyNYsCZ6WcaxFYHhDmLx9htw==

artifacts:
  - path: dist
    name: WPM-Frontend
    type: zip

install:
  - nvm use 15
  - npm ci --prefer-offline

cache:
  - "/home/appveyor/.npm"
  - node_modules

build_script:
  # Bundle sources
  - npm run build

test_script:
  # Add proper tests
  - npm run lint

deploy_script:
  - chmod +x deploy.sh
  - sh: ./deploy.sh

  # We do not want to build git tags.
skip_tags: true

# Use integers as build versions (1, 2, 3, …) instead of 1.0.X.
version: "{build}"