version: "3"

services:
  wpm-frontend:
    build:
      context: .
      args:
        VUE_APP_SERVER_URL: "http://pa.lubojanski.me" # Zu ersetzen
    restart: always
    networks:
      - web
      - wpm
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`pa.lubojanski.me`) # Zu ersetzen
      - traefik.http.routers.plex.entrypoints=web
    
networks:
  web:
    external: true

  wpm:
    external: true